functionsDirectory = "/Volumes/Personal/Work/Onboarding-Form/multi-step-form/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Volumes/Personal/Work/Onboarding-Form/multi-step-form/dist"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "/Volumes/Personal/Work/Onboarding-Form/multi-step-form/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
functions = "netlify/functions"
publish = "dist"
framework = "vite"

[functions]

[functions."*"]
external_node_modules = ["axios", "express", "cors", "serverless-http", "dotenv"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/server/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]